# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swifty Companion' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swifty Companion
	pod "OAuth2"
	pod "Alamofire"
	pod 'SwiftyJSON', '~> 4.0'
	pod "AlamofireImage"
	pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
end
